#!/usr/bin/env node
/**
 * sync:types — regenerate src/types/content.ts from the API's published schema (spec §8.4).
 *
 * The API exposes `GET /api/schema` (a JSON Schema derived from the canonical Zod
 * definitions in portfolio-v6-api/src/schemas/). This script fetches it and rewrites the
 * committed types file so the three repos never drift. CI re-runs it and fails if the
 * working tree changes.
 *
 * OFFLINE BEHAVIOUR: when the API is unreachable (the case in local/CI verification here),
 * the committed src/types/content.ts is authoritative — the script prints a notice and
 * exits 0 without touching the file. Only a reachable API rewrites it.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, '../src/types/content.ts');

// Mirror the app's env convention (§9.6). Empty base means same-origin, so fall back to
// the local dev API (§10) for a CLI run.
const base = (process.env.VITE_API_BASE_URL || 'http://localhost:3002').replace(/\/$/, '');
const schemaUrl = `${base}/api/schema`;

const HEADER = `/**
 * GENERATED — DO NOT EDIT BY HAND.
 * Regenerated by \`npm run sync:types\` from ${schemaUrl} (spec §8.4).
 */
`;

/** Minimal JSON Schema -> TypeScript conversion, sufficient for the content schema (§3). */
function tsType(schema) {
  if (!schema || typeof schema !== 'object') return 'unknown';
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => JSON.stringify(v)).join(' | ');
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (Array.isArray(schema.anyOf)) return schema.anyOf.map(tsType).join(' | ');
  if (Array.isArray(schema.oneOf)) return schema.oneOf.map(tsType).join(' | ');
  if (schema.$ref) return schema.$ref.replace(/^#\/(?:definitions|\$defs)\//, '');

  switch (schema.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array':
      return `${tsType(schema.items)}[]`;
    case 'object':
      return objectType(schema);
    default:
      return 'unknown';
  }
}

function objectType(schema) {
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const lines = Object.entries(props).map(([key, value]) => {
    const optional = required.has(key) ? '' : '?';
    return `  ${key}${optional}: ${tsType(value)};`;
  });
  return `{\n${lines.join('\n')}\n}`;
}

function render(schema) {
  const defs = schema.definitions ?? schema.$defs ?? {};
  const blocks = Object.entries(defs).map(([name, def]) => {
    const body = tsType(def);
    return body.startsWith('{')
      ? `export interface ${name} ${body}\n`
      : `export type ${name} = ${body};\n`;
  });
  return `${HEADER}\n${blocks.join('\n')}`;
}

async function main() {
  let response;
  try {
    response = await fetch(schemaUrl, { headers: { accept: 'application/json' } });
  } catch (err) {
    console.warn(
      `[sync:types] API unreachable at ${schemaUrl} (${err.message}). ` +
        'Keeping the committed src/types/content.ts, which is authoritative for now.',
    );
    return;
  }

  if (!response.ok) {
    console.warn(
      `[sync:types] ${schemaUrl} returned ${response.status}. Leaving the committed types unchanged.`,
    );
    return;
  }

  const schema = await response.json();
  await writeFile(OUTPUT, render(schema), 'utf8');
  console.log(`[sync:types] Wrote ${OUTPUT} from ${schemaUrl}.`);
}

main().catch((err) => {
  console.error('[sync:types] Unexpected failure:', err);
  process.exit(1);
});
